# Generated by Django 2.1 on 2020-06-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('total_vol', models.FloatField()),
                ('plu1', models.FloatField()),
                ('plu2', models.FloatField()),
                ('plu3', models.FloatField()),
                ('bags_t', models.FloatField()),
                ('bags_s', models.FloatField()),
                ('bags_l', models.FloatField()),
                ('bags_lx', models.FloatField()),
                ('type', models.TextField(max_length=1)),
                ('year', models.IntegerField()),
                ('location', models.TextField(max_length=25)),
            ],
        ),
    ]
