# Generated by Django 2.1 on 2020-06-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200604_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='product',
            name='date_w',
            field=models.DateTimeField(default='1000-10-10'),
        ),
    ]
