# Generated by Django 2.1 on 2020-06-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200604_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_w',
        ),
    ]
