# Generated by Django 2.1 on 2020-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_remove_product_date_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_w',
            field=models.DateField(null=True),
        ),
    ]
