# Generated by Django 2.1 on 2020-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20200604_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_w',
            field=models.DateField(),
        ),
    ]
